{
 "title": "MLOps Demo",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Model Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "ML API Health", "type": "alertlist", "gridPos": { "h": 8, "w": 3, "x": 0, "y": 1 } },
  {
   "title": "Model Error Monitoring",
   "type": "graph",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Model A",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "predicted_house_price",
     "query": "SELECT sqrt(mean(\"median_house_value\")) FROM \"autogen\".\"predicted_house_price\" WHERE (\"model\" = 'A') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "median_house_value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "model", "operator": "=", "value": "A" }
     ]
    },
    {
     "alias": "Model B",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "predicted_house_price",
     "query": "SELECT sqrt(mean(\"median_house_value\")) FROM \"autogen\".\"predicted_house_price\" WHERE (\"model\" = 'B') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "median_house_value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "model", "operator": "=", "value": "B" }
     ]
    }
   ]
  },
  {
   "title": "Feature A Monitoring",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Feature A",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "predicted_house_price",
     "select": [
      [
       { "params": [ "average_house_occupancy" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Feature B Monitoring",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Feature B",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "predicted_house_price",
     "select": [
      [
       { "params": [ "average_house_occupancy" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Feature C Monitoring",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Feature C",
     "measurement": "predicted_house_price",
     "select": [
      [
       { "params": [ "median_income_in_block" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  { "title": "Service Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Requests Total",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(fastapi_model_http_requests_total)"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 3, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(fastapi_model_http_request_duration_seconds_bucket[5m])) by (le)) * 1000"
    }
   ]
  },
  {
   "title": "Request Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 11, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "RPS" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fastapi_model_http_requests_total{status=\"2xx\"}[1m]))",
     "legendFormat": "{status=\"2xx\"}"
    },
    {
     "expr": "sum(rate(fastapi_model_http_requests_total{status=\"4xx\"}[1m]))",
     "legendFormat": "{status=\"4xx\"}"
    },
    {
     "expr": "sum(rate(fastapi_model_http_requests_total{status=\"5xx\"}[1m]))"
    }
   ]
  },
  {
   "title": "Messages in Queue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rabbitmq_queue_messages" }
   ]
  }
 ]
}